default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_quest_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: rails_quest_test
  url: <%= ENV["TEST_DATABASE_URL"] || ENV["DATABASE_URL"]&.sub("rails_quest_development", "rails_quest_test") %>

production:
  <<: *default
  <% if ENV["DATABASE_URL"].present? %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  database: <%= ENV.fetch("POSTGRES_DB") { "rails_runner_production" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "rails_runner" } %>
  password: <%= ENV["RAILS_RUNNER_DATABASE_PASSWORD"] || ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  <% end %>
