default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_quest_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: rails_quest_test
  url: <%= ENV["TEST_DATABASE_URL"] || ENV["DATABASE_URL"]&.sub("rails_quest_development", "rails_quest_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
